name = "cosmicverse-landing"
compatibility_date = "2024-07-01"

[env.production]
name = "cosmicverse-landing"

[[env.production.route]]
pattern = "cosmicverse.cloud/*"

[assets]
directory = "./out"
binding = "ASSETS"

[build]
command = "npm run build"
cwd = "./"
watch_dir = "src"

[vars]
NODE_ENV = "production" 